name: rigaku_smartlab
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ruff
  - pandas
  - numpy
  - seaborn
  - scipy
  - scikit-learn
  - scikit-image
  - ipykernel
  - pip:
    - python-dotenv
    - mkdocs
    - xrayutilities
    - lmfit
    - -e .